### ISSUE TITLE
need support for "relaxed" phylip output

### ISSUE THREAD

**Issue by nhoffman** [fhcrc/seqmagick#5]
'seqmagick convert from.whatever to.phy' raises an error when sequence names are not unique when truncated to 10 characters. It would be useful to have a --relaxed parameter (or some signal) that would suppress the strict 10 character name limit in phylip files (this appears to be the most practical format for raxml). Here's an example of the error:

```
Traceback (most recent call last):
  File "/home/nhoffman/bin/seqmagick", line 246, in <module>
    sys.exit(main())
  File "/home/nhoffman/bin/seqmagick", line 73, in main
    upper=arguments.upper,
  File "/home/nhoffman/lib/python2.7/site-packages/seqmagick/magickwrap.py", line 287, in transform
    SeqIO.write(records, destination_file, destination_file_type)
  File "/home/nhoffman/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 415, in write
    alignment_count = AlignIO.write([alignment], handle, format)
  File "/home/nhoffman/lib/python2.7/site-packages/Bio/AlignIO/__init__.py", line 209, in write
    count = writer_class(handle).write_file(alignments)
  File "/home/nhoffman/lib/python2.7/site-packages/Bio/AlignIO/Interfaces.py", line 118, in write_file
    self.write_alignment(alignment)
  File "/home/nhoffman/lib/python2.7/site-packages/Bio/AlignIO/PhylipIO.py", line 56, in write_alignment
    raise ValueError("Repeated identifier, possibly due to truncation")
ValueError: Repeated identifier, possibly due to truncation
```

And a code snippet for the relaxed phylip format:

```
from Bio import SeqIO
with open(outfile,'w+') as fout:
    # reserve some room on the first line
    fout.write(' '*80 + '\n')

    for i, seq in enumerate(SeqIO.parse(infile, "stockholm")):
        fout.write(' '.join([seq.name, seq.seq.tostring()]) + '\n')

    # now back to the top for the nseq, seqwidth header
    fout.seek(0)
    fout.write('%s %s' % (i, len(seq)))  
```

**Comment by EricaBarroso** [comment]
I have the same problem.
ubuntu@erica:~/data_concat/9septb$ seqmagick convert --input-format fasta --output-format phylip --alphabet dna id2_trnS-trnG.fasta trnS-trnG.phyx
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/seqmagick", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/seqmagick/scripts/cli.py", line 29, in main
    return action(arguments)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/seqmagick/subcommands/convert.py", line 347, in action
    transform_file(src, dest, arguments)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/seqmagick/subcommands/convert.py", line 311, in transform_file
    SeqIO.write(records, destination_file, destination_file_type)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 488, in write
    alignment_count = AlignIO.write([alignment], fp, format)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/Bio/AlignIO/__init__.py", line 216, in write
    count = writer_class(fp).write_file(alignments)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/Bio/AlignIO/Interfaces.py", line 133, in write_file
    self.write_alignment(alignment)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/Bio/AlignIO/PhylipIO.py", line 110, in write_alignment
    % (name, record.id))
ValueError: Repeated name 'Elytraria_' (originally 'Elytraria_caroliniensis'), possibly due to truncation
