### ISSUE TITLE
SIGPIPE problem in Windows

### ISSUE THREAD

**Issue by ladykiyenz** [fhcrc/seqmagick#58]
Not sure if Windows support is a priority but:

 **seqmagick info s20dataonly.snps**
Traceback (most recent call last):
  File "c:\users\katie\anaconda3\envs\py27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\katie\anaconda3\envs\py27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Katie\Anaconda3\envs\py27\Scripts\seqmagick.exe\__main__.py", line 9, in <module>
  File "c:\users\katie\anaconda3\envs\py27\lib\site-packages\seqmagick\scripts\cli.py", line 29, in main
    return action(arguments)
  File "c:\users\katie\anaconda3\envs\py27\lib\site-packages\seqmagick\subcommands\info.py", line 153, in action
    common.exit_on_sigpipe()
  File "c:\users\katie\anaconda3\envs\py27\lib\site-packages\seqmagick\subcommands\common.py", line 212, in exit_on_sigpipe
    _exit_on_signal(signal.SIGPIPE, status)
AttributeError: 'module' object has no attribute 'SIGPIPE'

Thanks!

**Comment by matsen** [comment]
Gee, sorry, none of us run Windows. 

However, are you running Python 3? Seqmagick is Python 2.

**Comment by ladykiyenz** [comment]
I opened a Python 2 environment both to install and attempt to run
seqmagick. I run it on all my other non-Windows machines so it's not a
priority for me, but I thought you should know.

Katie
