### ISSUE TITLE
fasta to nexus conversion -- ValueError: Sequences must all be the same length

### ISSUE THREAD

**Issue by asttra** [fhcrc/seqmagick#81]
Can anyone tell me why I am getting this error and how to fix it? 

`/projects/nanopore-working/niki/bin/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: This module has been deprecated. We encourage users to switch to alternative libraries implementing a trie data structure, for example pygtrie.`

 `return f(*args, **kwds)`

`/projects/nanopore-working/niki/bin/anaconda3/lib/python3.6/site-packages/Bio/triefind.py:34: BiopythonDeprecationWarning: This module has been deprecated. We encourage users to switch to alternative libraries implementing a trie data structure, for example pygtrie.`

 `"for example pygtrie.", BiopythonDeprecationWarning)`

`Traceback (most recent call last):
  File "/projects/nanopore-working/niki/bin/anaconda3/bin/seqmagick", line 10, in <module>
    sys.exit(main())
  File "/projects/nanopore-working/niki/bin/anaconda3/lib/python3.6/site-packages/seqmagick/scripts/cli.py", line 29, in main
    return action(arguments)
  File "/projects/nanopore-working/niki/bin/anaconda3/lib/python3.6/site-packages/seqmagick/subcommands/convert.py", line 354, in action
    transform_file(src, dest, arguments)
  File "/projects/nanopore-working/niki/bin/anaconda3/lib/python3.6/site-packages/seqmagick/subcommands/convert.py", line 318, in transform_file
    SeqIO.write(records, destination_file, destination_file_type)
  File "/projects/nanopore-working/niki/bin/anaconda3/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 537, in write
    alignment = MultipleSeqAlignment(sequences)
  File "/projects/nanopore-working/niki/bin/anaconda3/lib/python3.6/site-packages/Bio/Align/__init__.py", line 170, in __init__
    self.extend(records)
  File "/projects/nanopore-working/niki/bin/anaconda3/lib/python3.6/site-packages/Bio/Align/__init__.py", line 531, in extend
    self._append(rec, expected_length)
  File "/projects/nanopore-working/niki/bin/anaconda3/lib/python3.6/site-packages/Bio/Align/__init__.py", line 594, in _append
    raise ValueError("Sequences must all be the same length")`

`ValueError: Sequences must all be the same length`

**Comment by eharkins** [comment]
@asttra since you are converting to [nexus format](https://bioperl.org/formats/alignment_formats/NEXUS_multiple_alignment_format) I think you must have your sequences aligned / all the same length.

**Comment by evolozzy** [comment]
you can use `muscle` to align your sequences to same length
