### ISSUE TITLE
convert from fasta fails on stable biopython (Bio.Alphabet has been removed from Biopython)

### ISSUE THREAD

**Issue by wwood** [fhcrc/seqmagick#87]
Just installed seqmagick from conda, then:
```
❯ seqmagick convert VOG00015.protein_ids.aln.faa.divvy.fas VOG00015.aln.phylip
Traceback (most recent call last):
  File "/home/woodcrob/e/seqmagick-0.8.0/bin/seqmagick", line 10, in <module>
    sys.exit(main())
  File "/home/woodcrob/e/seqmagick-0.8.0/lib/python3.8/site-packages/seqmagick/scripts/cli.py", line 12, in main
    action, arguments = parse_arguments(argv)
  File "/home/woodcrob/e/seqmagick-0.8.0/lib/python3.8/site-packages/seqmagick/scripts/cli.py", line 58, in parse_arguments
    for name, mod in subcommands.itermodules():
  File "/home/woodcrob/e/seqmagick-0.8.0/lib/python3.8/site-packages/seqmagick/subcommands/__init__.py", line 8, in itermodules
    __import__('%s.%s' % (root, command), fromlist=[command]))
  File "/home/woodcrob/e/seqmagick-0.8.0/lib/python3.8/site-packages/seqmagick/subcommands/convert.py", line 9, in <module>
    from Bio import Alphabet, SeqIO
  File "/home/woodcrob/e/seqmagick-0.8.0/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```
Apologies to have to report a boring bug as this.

**Comment by ReneKat** [comment]
Hello there, 
Same issue here.

**Comment by jgallowa07** [comment]
Closing, see #89 for details.
