### ISSUE TITLE
Error with --reverse-complement: random prefix of letters appended to fastq file name, causing failure to read.

### ISSUE THREAD

**Issue by jsacco1** [fhcrc/seqmagick#94]
Hi, 
I created a conda environment for seqmagick with biopython 1.76 and Python 3.5.5, then followed all the instructions for installation. I ran the following line from inside the same folder that contains the fastq.gz:

`seqmagick mogrify --reverse-complement ASC518-1-23P_S1_L001_I2_001.fastq.gz
`
And I got this traceback that adds random letters to the front of the filename. Any insight into what is going on? 

```
Traceback (most recent call last):
  File "/home/james/anaconda3/envs/sm/lib/python3.5/site-packages/seqmagick/subcommands/common.py", line 69, in atomic_write
    os.chmod(path, permissions)
PermissionError: [Errno 1] Operation not permitted: 'ASC518-1-23P_S1_L001_I2_001.fastq.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/james/anaconda3/envs/sm/bin/seqmagick", line 8, in <module>
    sys.exit(main())
  File "/home/james/anaconda3/envs/sm/lib/python3.5/site-packages/seqmagick/scripts/cli.py", line 29, in main
    return action(arguments)
  File "/home/james/anaconda3/envs/sm/lib/python3.5/site-packages/seqmagick/subcommands/mogrify.py", line 34, in action
    input_file.close()
  File "/home/james/anaconda3/envs/sm/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/james/anaconda3/envs/sm/lib/python3.5/site-packages/seqmagick/subcommands/common.py", line 71, in atomic_write
    os.remove(tf.name)
FileNotFoundError: [Errno 2] No such file or directory: '/home/james/Bioinformatics/guideseq/fastq/i2/seqmagick/tmpm1hhl0utASC518-1-23P_S1_L001_I2_001.fastq.gz'

```

It adds "tmpm1hhl0ut" to the front of the file name.

Thank you,
James

**Comment by jgallowa07** [comment]
@jsacco1 We require Biopython >= 1.78 . as noted in the README. This should probably be noted in the documentations, apologies.
